Unit test
ITU-BDSA2024-GROUP9/Chirp pull request #40
Opened 2024-11-02 00:03 UTC by DefaultDaddy

The code has been refactored a bit (To follow the same naming schemes). Additonally, there has been created unit tests, that has 100% test coverage for CheepService and CheepRepository.

2024-11-02 11:16 UTC, MrBStones approved these changes
Lgtm

2024-11-03 10:23 UTC, JKlarlund requested changes
Nice work!

2024-11-03 10:23 UTC, JKlarlund commented on test/Chirp.Razor.Tests/ChirpTests.cs
>          Assert.NotEmpty(result);
Maybe we need to change assert to check if the result is actually written by the author

2024-11-03 10:23 UTC, JKlarlund commented on test/Chirp.Razor.Tests/ChirpTests.cs
>          Assert.NotEmpty(result);
Same here

2024-11-03 10:23 UTC, JKlarlund commented on test/Chirp.Razor.Tests/ChirpTests.cs
>          Assert.NotNull(result);
And here

2024-11-03 10:34 UTC, JKlarlund approved these changes
Good work!

2024-11-03 10:34 UTC, merged